### ISSUE TITLE
Error using in an Array

### ISSUE THREAD

**Issue by Robbie188** [Textalk/angular-schema-form-base64-file-upload#2]
Hi there, when using this control in an array ngModel is not attached and therefore not passed to the directive `base64FileUpload`.  It gives the following error in js console:

```
[$compile:ctreq] Controller 'ngModel', required by directive 'base64FileUpload', can't be found!
```

The control works perfectly outside of the array.

html:

```
<div class="form-content" ng-controller="formContentCtrl">
   <form>
      <div sf-schema="schema" sf-form="form" sf-model="model"></div>
   </form>
</div>
```

controller:

```
`angular.module('example', ['schemaForm', 'angularSchemaFormBase64FileUpload'])
.controller('exampleCtrl', function ($scope) {

$scope.model = {};

$scope.schema = {
    "type": "object",
    "title": "Example",
    "required": [

    ],
    "properties": {

        "fileUpload1": {
            "title": "Outsite of Array",
            "type": "string",
            "format": "base64",
            "maxSize": "500000"
      },

        "array": {
            "type": "array",
            "title": "Test Array",
            "items": {
                "type": "object",
                "properties": {
                    "fileUpload2": {
                        "title": "Inside the Array",
                        "type": "string",
                        "format": "base64",
                        "maxSize": "500000"
                    }
                },
                "required": [

                ]
            }
        }
    }
};

$scope.form = [
    {
        "type": "help",
        "helpvalue": "<h1>Example Form</h1>",
        "description": "test"
    },
    "fileUpload1",
    {
        "key": "array",
        "add": "Add",
        "style": {
            "add": "btn-success"
        },
        "items": [
            "array[].fileUpload2"
        ]
    }
];
});`
```

Any assistance with this would be greatly appreciated.

**Comment by kornosaurus** [comment]
@Robbie188 What angular schema form version are you using?

Works fine for me on 1.1.2 with angular schema form 0.8.13

**Comment by Robbie188** [comment]
Hey thanks for checking it out and getting back to me. That's weird because as far as I can tell i'm using the same versions, I'll look into it a bit more tonight though and see if I can find where I'm going wrong.  I'll get back to you.

**Comment by kornosaurus** [comment]
@Robbie188 No problem! from what I can see the scope variables used in the html is different from the ones in your controller, however I guess you used copy pasted some code to be used as an example..

I tested this with your `form` and `schema` in the `demo/index.html` of this project.. Maybe you should try that and maybe you can see the difference from what you have in your project... (just run `gulp` to start up a server)

**Comment by jmmcatee** [comment]
I am having this same issue with conditionals. Any thoughts here?

**Comment by jmmcatee** [comment]
It is not working for me. Not sure what I did here, but I am good now.

**Comment by kornosaurus** [comment]
@jmmcatee Can you post your form and schema so i could test it out?

**Comment by jmmcatee** [comment]
@kornosaurus I can link you to the software once we release this next version. It is working now. I think I was just seeing an error that was unrelated initially.

**Comment by kornosaurus** [comment]
@Robbie188 Any updates on this?

**Comment by Robbie188** [comment]
@kornosaurus apologies for delay.  So I did what you said and tested in demo/index.html and the control works fine inside of an array. So I figured as you suggested it must be something to do with the versions of other dependencies in my app.  Hopefully in next couple of days I can work out the exact cause and I'll post it back here in case anyone else has the same issue.

**Comment by kornosaurus** [comment]
@Robbie188 Okey, let's hope you can find the problem in your app, would love to hear what went wrong, it might aswell be a bug from this add-on. I'm keeping this issue open in the meanwhile.

**Comment by Robbie188** [comment]
@kornosaurus It seems in my app I was unintentionally using a different bootstrap decorator.  Once I changed it to use the  same bootstrap decorator as the one in the demo it worked fine.  Previously I was using `angular-schema-form/dist/bootstrap-decorator.js` which has issue using the control inside of the array.  Using `angular-schema-form-bootstrap/bootstrap-decorator.min.js` it works fine now.  Thanks for your assistance!
