### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by navjinder** [Textalk/angular-schema-form-base64-file-upload#3]
Here is my **form** code
`{
                    type : 'section',
                    htmlClass : 'col-sm-12',
                    items : [{
                        key : 'cover',
                        type : 'base64file'
                    }]
                }`

and my **schema**
`
cover: {
      title: 'Upload Cover',
      type: 'string',
      format: 'base64',
      maxSize: '500000'
    }
`
But it just gives an input field.

**Comment by kornosaurus** [comment]
Did you load the angular module? 

`angular.module('myApp', ["schemaForm","angularSchemaFormBase64FileUpload"])`

**Comment by navjinder** [comment]
Hi There

This is not required as all the modules for schema form are already inject within the 'schemaform' I have used other plugins without defining it in the DI and they work.

**Comment by kornosaurus** [comment]
This is not the case with this add-on, though I think it should be. (https://github.com/Textalk/angular-schema-form-base64-file-upload/blob/master/src/module.js#L1) however I do not really have time to fix this, you could make a PR or just inject the module like i suggested :)

**Comment by navjinder** [comment]
Yes, you are right I checked your code structure it was different. See [Dynamic Select](https://github.com/OptimalBPM/angular-schema-form-dynamic-select) for more details. I tried injecting it but it gave an error; However, I solved it by using [angular-base-64-upload](https://github.com/adonespitogo/angular-base64-upload). Thanks a lot.

**Comment by kornosaurus** [comment]
in this file you can see how to inject and use it :) https://github.com/Textalk/angular-schema-form-base64-file-upload/blob/master/demo/index.html
